### PR TITLE
Use nsls2forge docker image for building on Linux

### PR DESCRIPTION
**Pull request by mrakitin**
Also, minor reformats of the recipe file.

### CODE REVIEW

**Comment by st3107** [comment]
Reopen to rerun the CI.

**Comment by mrakitin** [comment]
@st3107, it is missing the following dependencies:
  - `pyxdameraulevenshtein`
  - `xpdtools`
  - `xpdview`

**Comment by st3107** [comment]
Thank you @mrakitin . They are on conda-forge. I wonder if I can add conda-forge in the conda_build_config file.

**Comment by st3107** [comment]
Thank you. I will move them on to the nsls-ii-forge.

**Comment by mrakitin** [comment]
> Thank you @mrakitin . They are on conda-forge. I wonder if I can add conda-forge in the conda_build_config file.

Please don't do it. We better rebuild them in our channel as we plan to deploy a single environment on the floor, and prefer to avoid shadowing of the channels.

**Comment by mrakitin** [comment]
@st3107, this comment concerns me: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/blob/df8c94bec9d233b1c13e8c261005bae853eb5485/recipe/meta.yaml#L17-L19

Do you think it's resolved now, and we can use Python >3.6?

**Comment by st3107** [comment]
I wll confirm with CJ.

**Comment by mrakitin** [comment]
I asked it here just in case: https://github.com/conda-forge/pyxdameraulevenshtein-feedstock/issues/19.

**Pull request merged**
